services:
  - type: web
    name: aurora-bulk-mailer
    runtime: node
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: APP_USER
        sync: false
      - key: APP_PASS
        sync: false
