services:
  - type: web
    name: aurora-bulk-mailer
    runtime: node
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: APP_USER
        sync: false
      - key: APP_PASS
        sync: false
      - key: GAS_MAIL_URL
        value: https://script.google.com/macros/s/AKfycbxdHKEV-bA1Db1PiUrEH--SL0UOw_13ZfKy0w3a_G2IF86Bt51Z3f90N7JN7MgKWn8J/exec
